### ISSUE TITLE
A little hope

### ISSUE THREAD

**Issue by JericoFX** [Trololp/Small-utils#1]
i can express the happynes i fell to see that someone can do an unpacker and packer for avp2010, the most unrelated game, i love it and i want to update all the textures for the game, but all the tutorials point to older unpakers that doesnt not work at all, i dont know if you gonna finish this, but man, i appreciate it!

**Comment by JericoFX** [comment]
belive me or not, i manage to compile the Asura descompiler and it work!!! you made my dream come true!

**Comment by Trololp** [comment]
Glad it help you. But I am not doing stuff with asura engine anymore.

**Comment by JericoFX** [comment]
I want to ask if I can use your work to release to the public, because does not have a license, I want to make a new tutorial about how to mod avp2010, of course all the credits will go to you
